# Generated by Django 4.0.2 on 2022-03-23 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(editable=False, max_length=20, verbose_name='评论ID')),
                ('comment_target', models.CharField(max_length=20, verbose_name='评论对象')),
                ('status', models.CharField(choices=[('SU', '评论成功'), ('CA', '评论取消'), ('VI', '评论违规')], default='SU', max_length=2, verbose_name='评论状态')),
                ('out_vender', models.CharField(blank=True, max_length=100, null=True, verbose_name='评论渠道')),
                ('comment_title', models.CharField(max_length=120, verbose_name='评论标题')),
                ('comment', models.CharField(max_length=5000, verbose_name='评论内容')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.user', verbose_name='作者')),
            ],
            options={
                'verbose_name': 'Comment',
            },
        ),
    ]
