# Generated by Django 4.0.2 on 2022-04-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['cid'], 'verbose_name': 'Comment'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_target',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='out_vender',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_subtitle',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='评论副标题'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=5000, verbose_name='评论内容'),
        ),
    ]
