# Generated by Django 4.0.2 on 2022-04-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_comment_options_remove_comment_comment_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subcomment',
            field=models.CharField(default='暂无', max_length=100, verbose_name='评论简介'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.CharField(editable=False, max_length=200, verbose_name='评论ID'),
        ),
    ]
