# Generated by Django 4.0.2 on 2022-05-02 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_carbon_order_searchrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='评论时间'),
            preserve_default=False,
        ),
    ]
